version: '2'
volumes:
  mc-sharedclasses:
    driver: local
services:
  mc1:
    ports:
      - "25565:25565"
    volumes:
      - /home/dkraemer/mc1:/data
      - mc-sharedclasses:/shared
    image: luitzifa/minecraft-server-light
    environment:
      ICON: 'http://i.imgur.com/6V9U5hZ.png'
      MOTD: 'strange things gonna happen here'
      JVM_OPTS: '-Xmx1024M -Xms1024M -Xshareclasses:cacheDir=/shared'
      EULA: 'TRUE'
      OPS: 'Luitzifa,nobody'
      WHITELIST: 'Luitzifa,nobody'
      MODE: 'survival'
      DIFFICULTY: 'normal'
      ALLOW_NETHER: 'true'
      SPAWN_ANIMALS: 'true'
      SPAWN_MONSTERS: 'true'
      SPAWN_NPCS: 'true'
      GENERATE_STRUCTURES: 'true'
      UID: 1000
      GID: 1000
    network_mode: "bridge"
    tty: true
    stdin_open: true
    restart: always
  mc2:
    ports:
      - "25566:25565"
    volumes:
      - /home/dkraemer/mc2:/data
      - mc-sharedclasses:/shared
    image: luitzifa/minecraft-server-light
    environment:
      ICON: 'http://i.imgur.com/6V9U5hZ.png'
      MOTD: 'strange things gonna happen here'
      JVM_OPTS: '-Xmx1024M -Xms1024M -Xshareclasses:cacheDir=/shared'
      EULA: 'TRUE'
      OPS: 'Luitzifa,nobody'
      WHITELIST: 'Luitzifa,nobody'
      MODE: 'creative'
      DIFFICULTY: 'normal'
      ALLOW_NETHER: 'true'
      SPAWN_ANIMALS: 'false'
      SPAWN_MONSTERS: 'false'
      SPAWN_NPCS: 'false'
      GENERATE_STRUCTURES: 'true'
      UID: 1000
      GID: 1000
    network_mode: "bridge"
    tty: true
    stdin_open: true
    restart: always
